INSERT INTO `locations` (`id`, `name`, `group_level`, `improv_type`, `location`, `date_established`, `nospacename`, `urlcity`)
VALUES
  (1, 'ACME Comedy Theatre', 'Professional', 'Theatresports', 'Los Angeles, California', '1989', 'ACME+Comedy+Theatre', 'Los+Angeles,California'),
  (2, 'American Improv Theatre', 'Professional', 'Long-form, Musicals', 'San Jose, California', '2015', 'American+Improv+Theatre', 'San+Jose,California'),
  (3, 'Awkward Compliment', 'Professional', 'Improvisational', 'Somerville, Massachusetts', '2010', 'Awkward+Compliment', 'Somerville,Massachusetts'),
  (4, 'The Annoyance Theatre', 'Professional', 'Improvisational', 'Chicago, Illinois', '1987', 'The+Annoyance+Theatre', 'Chicago,Illinois'),
  (5, 'Arcade Comedy Theater', 'Professional', 'Multiple', 'Pittsburgh, Pennsylvania', '2013', 'Arcade+Comedy+Theater', 'Pittsburgh,Pennsylvania'),
  (6, 'Atlas Improv Co.', 'Professional', 'Multiple', 'Madison, Wisconsin', '2004', 'Atlas+Improv+Co.', 'Madison,Wisconsin'),
  (7, 'Baltimore Improv Group', 'Professional', 'Multiple', 'Baltimore, Maryland', '2004', 'Baltimore+Improv+Group', 'Baltimore,Maryland'),
  (8, 'Bay Cities Improv Company', 'Professional', 'Shortform', 'Mobile, Alabama', '2013', 'Bay+Cities+Improv+Company', 'Mobile,Alabama'),
  (9, 'BATS Improv', 'Major Professional', 'Theatresports', 'San Francisco, California', '1986', 'BATS+Improv', 'San+Francisco,California'),
  (10, 'BETA Theater', 'Professional', 'Multiple', 'Houston, TX', '2013', 'BETA+Theater', 'Houston,TX'),
  (11, 'The Bent Theatre', 'Professional', 'Multiple', 'Charlottesville, Virginia', '2004', 'The+Bent+Theatre', 'Charlottesville,Virginia'),
  (12, 'Black Sheep Improv', 'Collegiate', 'Long-Form', 'Athens, Ohio', '2007', 'Black+Sheep+Improv', 'Athens,Ohio'),
  (13, 'Bovine Metropolis Theater', 'Professional', 'Multiple', 'Denver, Colorado', '1998', 'Bovine+Metropolis+Theater', 'Denver,Colorado'),
  (14, 'Boulder Improv Collaborative', 'Professional', 'Multiple', 'Boulder, Colorado', '2004', 'Boulder+Improv+Collaborative', 'Boulder,Colorado'),
  (15, 'The Brave New Workshop Comedy Theatre', 'Professional', 'Multiple', 'Minneapolis, Minnesota', '1958', 'The+Brave+New+Workshop+Comedy+Theatre', 'Minneapolis,Minnesota'),
  (16, 'Carolina Improv Company', 'Professional', 'Multiple', 'Myrtle Beach, South Carolina', '2008', 'Carolina+Improv+Company', 'Myrtle+Beach,South+Carolina'),
  (17, 'Charlotte Comedy Theater', 'Professional', 'Multiple', 'Charlotte, North Carolina', '2001', 'Charlotte+Comedy+Theater', 'Charlotte,North+Carolina'),
  (18, 'Charm City Comedy Project', 'Professional', 'Multiple', 'Baltimore, Maryland', '2014', 'Charm+City+Comedy+Project', 'Baltimore,Maryland'),
  (19, 'CHiPs Improv', 'Collegiate', 'Multiple', 'Chapel Hill, North Carolina', '1995', 'CHiPs+Improv', 'Chapel+Hill,North+Carolina'),
  (20, 'Coalition Theater', 'Professional', 'Multiple', 'Richmond, Virginia', '2009', 'Coalition+Theater', 'Richmond,Virginia'),
  (21, 'Columbus Unscripted', 'Professional', 'Improvisational', 'Columbus, Ohio', '2006', 'Columbus+Unscripted', 'Columbus,Ohio'),
  (22, 'ComedyCity', 'Professional', 'Shortform', 'Green Bay, Wisconsin', '1987', 'ComedyCity', 'Green+Bay,Wisconsin'),
  (23, 'Comedy Corner', 'Collegiate', 'Multiple', 'Tucson, Arizona', '1979', 'Comedy+Corner', 'Tucson,Arizona'),
  (24, 'Commedus Interruptus', 'Collegiate', 'Multiple', 'Los Angeles, California', '1989', 'Commedus+Interruptus', 'Los+Angeles,California'),
  (25, 'ComedySportz', 'Major Professional', 'Shortform', 'Milwaukee, Wisconsin', '1984', 'ComedySportz', 'Milwaukee,Wisconsin'),
  (26, 'The Crazy Monkeys', 'Collegiate', 'Shortform', 'West Lafayette, Indiana', '1988', 'The+Crazy+Monkeys', 'West+Lafayette,Indiana'),
  (27, 'Dad\'s Garage Theatre Company', 'Professional', 'Multiple', 'Atlanta, Georgia', '1995', 'Dad\'s+Garage+Theatre+Company', 'Atlanta,Georgia'),
  (28, 'Defiant Monkey Improv', 'Professional', 'Short-form', 'Buffalo, NY', '2009', 'Defiant+Monkey+Improv', 'Buffalo,NY'),
  (29, 'The Denials', 'The Overtime Theater', 'Short-form', 'San Antonio, Texas', '2009', 'The+Denials', 'San+Antonio,Texas'),
  (30, 'Eclectic Improv Co.', 'Professional', 'Short-Form', 'Buffalo, New York', '1998', 'Eclectic+Improv+Co.', 'Buffalo,New+York'),
  (31, 'Endgames Improv', 'Professional', 'Long-Form', 'San Francisco, California', '2010', 'Endgames+Improv', 'San+Francisco,California'),
  (32, 'Erasable Inc.', 'Collegiate', 'Improvisational', 'College Park, Maryland', '1986', 'Erasable+Inc.', 'College+Park,Maryland'),
  (33, 'Face Off Unlimited', 'Professional', 'Multiple', 'New York City, New York', '2003', 'Face+Off+Unlimited', 'New+York+City,New+York'),
  (34, 'False Profits Comedy', 'Collegiate', 'Multiple', 'Chapel Hill, North Carolina', '2013', 'False+Profits+Comedy', 'Chapel+Hill,North+Carolina'),
  (35, 'The First Time Offenders', 'Collegiate', 'Multiple', 'San Antonio, TX', '2008', 'The+First+Time+Offenders', 'San+Antonio,TX'),
  (36, 'The Focus Group', 'Professional', 'Long-form', 'Bangor, Maine', '2009', 'The+Focus+Group', 'Bangor,Maine'),
  (37, 'Freudian Slip', 'Collegiate', 'Improvisational', 'College Station, TX', '1994', 'Freudian+Slip', 'College+Station,TX'),
  (38, 'Friday Night Improvs', 'Collegiate', 'Improv Jam', 'Pittsburgh, Pennsylvania', '1989', 'Friday+Night+Improvs', 'Pittsburgh,Pennsylvania'),
  (39, 'Full Frontal Nudity', 'Professional', 'Multiple', 'Columbus, Ohio', '1993', 'Full+Frontal+Nudity', 'Columbus,Ohio'),
  (40, 'Good On Paper', 'Professional', 'Short-form', 'Traverse City, MI', '2010', 'Good+On+Paper', 'Traverse+City,MI'),
  (41, 'Groundlings', 'Major Professional', 'Semi-improvisational', 'Los Angeles, California', '1974', 'Groundlings', 'Los+Angeles,California'),
  (42, 'Harrisburg Improv Theatre', 'Professional', 'Long-form', 'Harrisburg, Pennsylvania', '2014', 'Harrisburg+Improv+Theatre', 'Harrisburg,Pennsylvania'),
  (43, 'HUGE Theater', 'Professional', 'Long-form', 'Minneapolis, Minnesota', '2005', 'HUGE+Theater', 'Minneapolis,Minnesota'),
  (44, 'The Immediate Gratification Players', 'Collegiate', 'Long-form', 'Cambridge, Massachusetts', '1986', 'The+Immediate+Gratification+Players', 'Cambridge,Massachusetts'),
  (45, 'ImprovOlympic', 'Major Professional', 'the Harold', 'Chicago, Illinois', '1980', 'ImprovOlympic', 'Chicago,Illinois'),
  (46, 'Improv Asylum', 'Major Professional', 'Semi-improvisational', 'Boston, Massachusetts', '1998', 'Improv+Asylum', 'Boston,Massachusetts'),
  (47, 'ImprovBoston', 'Major Professional', 'Multiple', 'Cambridge, Massachusetts', '1982', 'ImprovBoston', 'Cambridge,Massachusetts'),
  (48, 'Improv Everywhere', 'Professional', 'Guerrilla', 'New York City, New York', '2001', 'Improv+Everywhere', 'New+York+City,New+York'),
  (49, 'Improv Hawaii', 'Professional', 'Multiple', 'Honolulu, Hawaii', '2012', 'Improv+Hawaii', 'Honolulu,Hawaii'),
  (50, 'Improvhi', 'Professional', 'Multiple', 'Honolulu, Hawaii', '2012', 'Improvhi', 'Honolulu,Hawaii'),
  (51, 'The Improv Shop', 'Professional', 'Improvisational', 'Saint Louis, Missouri', '2009', 'The+Improv+Shop', 'Saint+Louis,Missouri'),
  (52, 'In Between The Lines Comedy Improv Troupe', 'Collegiate', 'Shortform', 'Rochester, New York', '1999', 'In+Between+The+Lines+Comedy+Improv+Troupe', 'Rochester,New+York'),
  (53, 'Jet City Improv', 'Professional', 'Multiple', 'Seattle, Washington', '1992', 'Jet+City+Improv', 'Seattle,Washington'),
  (54, 'Just Add Water', 'Collegiate', 'Improvisational', 'New Haven, Connecticut', '1986', 'Just+Add+Water', 'New+Haven,Connecticut'),
  (55, 'Just The Funny', 'Professional', 'Multiple', 'Miami, Florida', '1999', 'Just+The+Funny', 'Miami,Florida'),
  (56, 'Laughing Matters', 'Professional', 'Shortform', 'Atlanta, Georgia', '1985', 'Laughing+Matters', 'Atlanta,Georgia'),
  (57, 'Lee County Flannel Club', 'Collegiate', 'Shortform', 'Auburn, Alabama', '2011', 'Lee+County+Flannel+Club', 'Auburn,Alabama'),
  (58, 'Leela', 'Professional', 'Multiple', 'San Francisco, California', '2003', 'Leela', 'San+Francisco,California'),
  (59, 'The Lobby', 'Professional', 'Shortform', 'Fullerton, California', '2005', 'The+Lobby', 'Fullerton,California'),
  (60, 'Madcap Theater', 'Professional', 'Shortform', 'Westminster, Colorado', '2006', 'Madcap+Theater', 'Westminster,Colorado'),
  (61, 'Magnet Theater', 'Major Professional', 'Long-Form', 'New York City, New York', '2005', 'Magnet+Theater', 'New+York+City,New+York'),
  (62, 'Monkey Business Institute', 'Professional', 'Shortform', 'Madison, Wisconsin', '2004', 'Monkey+Business+Institute', 'Madison,Wisconsin'),
  (63, 'My Mother\'s Fleabag', 'Collegiate', 'Short-form', 'Chestnut Hill, Massachusetts', '1980', 'My+Mother\'s+Fleabag', 'Chestnut+Hill,Massachusetts'),
  (64, 'The N Crowd', 'Professional', 'Shortform', 'Philadelphia, Pennsylvania', '2005', 'The+N+Crowd', 'Philadelphia,Pennsylvania'),
  (65, 'The National Comedy Theatre', 'Major Professional', 'Shortform', 'San Diego, California', '2000', 'The+National+Comedy+Theatre', 'San+Diego,California'),
  (66, 'Odd Lot Improv', 'Professional', 'Shortform', 'Savannah, Georgia', '2010', 'Odd+Lot+Improv', 'Savannah,Georgia'),
  (67, 'On Thin Ice', 'Collegiate', 'Shortform', 'Cambridge, Massachusetts', '1984', 'On+Thin+Ice', 'Cambridge,Massachusetts'),
  (68, 'Peoples Improv Theater', 'Major Professional', 'Multiple', 'New York City, New York', '2002', 'Peoples+Improv+Theater', 'New+York+City,New+York'),
  (69, 'Philly Improv Theater (PHIT)', 'Major Professional', 'Multiple', 'Philadelphia, Pennsylvania', '2005', 'Philly+Improv+Theater+(PHIT)', 'Philadelphia,Pennsylvania'),
  (70, 'The Playground', 'Professional', 'Long-form', 'Chicago, Illinois', '1997', 'The+Playground', 'Chicago,Illinois'),
  (71, 'Providence Improv Guild', 'Professional', 'Multiple', 'Providence, Rhode Island', '2013', 'Providence+Improv+Guild', 'Providence,Rhode+Island'),
  (72, 'The Purple Crayon of Yale', 'Collegiate', 'Long-form', 'New Haven, Connecticut', '1985', 'The+Purple+Crayon+of+Yale', 'New+Haven,Connecticut'),
  (73, 'Sacramento Comedy Spot', 'Major Professional', 'Multiple', 'Sacramento, California', '2004', 'Sacramento+Comedy+Spot', 'Sacramento,California'),
  (74, 'SAK Comedy Lab', 'Professional', 'Multiple', 'Orlando, Florida', '1991', 'SAK+Comedy+Lab', 'Orlando,Florida'),
  (75, 'The San Francisco Improv Alliance', 'Professional', 'Multiple', 'San Francisco, California', '2005', 'The+San+Francisco+Improv+Alliance', 'San+Francisco,California'),
  (76, 'The San Francisco Improv Co-Operative', 'Professional', 'Multiple', 'San Francisco, California', '2000', 'The+San+Francisco+Improv+Co-Operative', 'San+Francisco,California'),
  (77, 'San Francisco Improv Collective', 'Professional', 'Multiple', 'San Francisco, California', '2013', 'San+Francisco+Improv+Collective', 'San+Francisco,California'),
  (78, 'Sea Tea Improv', 'Professional', 'Multiple', 'Hartford, Connecticut', '2009', 'Sea+Tea+Improv', 'Hartford,Connecticut'),
  (79, 'The Second City', 'Major Professional', 'Semi-improvisational', 'Chicago, Illinois', '1959', 'The+Second+City', 'Chicago,Illinois'),
  (80, 'Second Nature Improv', 'Collegiate', 'Long-form', 'Los Angeles, California', '2002', 'Second+Nature+Improv', 'Los+Angeles,California'),
  (81, 'SEE Saw Comedy', 'Professional', 'Multiple', 'Sayville, NY', '2006', 'SEE+Saw+Comedy', 'Sayville,NY'),
  (82, 'Sick Puppies Comedy', 'Professional', 'Multiple', 'Boca Raton, Florida', '2012', 'Sick+Puppies+Comedy', 'Boca+Raton,Florida'),
  (83, 'Silverbacks Improv Theatre', 'Professional', 'Multiple', 'Lafayette, Louisiana', '2012', 'Silverbacks+Improv+Theatre', 'Lafayette,Louisiana'),
  (84, 'State Theatre Improv Fun Force', 'Professional', 'Multiple', 'Eustis, FL', '2015', 'State+Theatre+Improv+Fun+Force', 'Eustis,FL'),
  (85, 'Starla and Sons', 'Collegiate', 'Longform', 'Providence, Rhode Island', '2006', 'Starla+and+Sons', 'Providence,Rhode+Island'),
  (86, 'Steel City Improv Theater', 'Professional', 'Longform', 'Pittsburgh, PA', '2010', 'Steel+City+Improv+Theater', 'Pittsburgh,PA'),
  (87, 'Syracuse Improv Collective', 'Professional', 'Multiple', 'Syracuse, New York', '2011', 'Syracuse+Improv+Collective', 'Syracuse,New+York'),
  (88, 'Theatre 99', 'Professional', 'Multiple', 'Charleston, South Carolina', '2000', 'Theatre+99', 'Charleston,South+Carolina'),
  (89, 'Theatre Strike Force', 'Collegiate', 'Multiple', 'Gainesville, Florida', '1989', 'Theatre+Strike+Force', 'Gainesville,Florida'),
  (90, 'Tucson Improv Movement', 'Professional', 'Multiple', 'Tucson, Arizona', '2012', 'Tucson+Improv+Movement', 'Tucson,Arizona'),
  (91, 'The National Comedy Theatre', 'Professional', 'Multiple', 'Phoenix, Arizona', '2007', 'The+National+Comedy+Theatre', 'Phoenix,Arizona'),
  (92, 'Unexpected Company', 'Professional', 'Long-form', 'Warwick, Rhode Island', '2003', 'Unexpected+Company', 'Warwick,Rhode+Island'),
  (93, 'Unexpected Productions', 'Professional', 'Theatresports', 'Seattle, Washington', '1983', 'Unexpected+Productions', 'Seattle,Washington'),
  (94, 'Under the Gun Theater', 'Professional', 'Multiple', 'Chicago, Illinois', '2014', 'Under+the+Gun+Theater', 'Chicago,Illinois'),
  (95, 'The Un-Scripted Theater Company', 'Professional', 'Multiple', 'San Francisco, California', '2002', 'The+Un-Scripted+Theater+Company', 'San+Francisco,California'),
  (96, 'Upright Citizens Brigade', 'Major Professional', 'Multiple', 'New York City, New York', '1999', 'Upright+Citizens+Brigade', 'New+York+City,New+York'),
  (97, 'Vaudeville Performing Arts (Vaudeville Central Florida)', 'Professional', 'Short Form/Improvisational', 'Orlando, Florida', '2015', 'Vaudeville+Performing+Arts+(Vaudeville+Central+Florida)', 'Orlando,Florida'),
  (98, 'Washington Improv Theater', 'Major Professional', 'Long-form', 'Washington, DC', '1995', 'Washington+Improv+Theater', 'Washington,DC'),
  (99, 'Whole World Theatre', 'Professional', 'Shortform', 'Atlanta, Georgia', '1994', 'Whole+World+Theatre', 'Atlanta,Georgia'),
  (100, 'Wing-It Productions', 'Professional', 'Multiple', 'Seattle, Washington', '1992', 'Wing-It+Productions', 'Seattle,Washington'),
  (101, 'The Yale Ex!t Players', 'Collegiate', 'Short-form', 'New Haven, Connecticut', '1984', 'The+Yale+Ex!t+Players', 'New+Haven,Connecticut'),
  (102, 'WHIP Comedy Improv', 'Collegiate', 'Multiple', 'Westfield, Massachusetts', '2012', 'WHIP+Comedy+Improv', 'Westfield,Massachusetts');