INSERT INTO `locations` (`id`, `name`, `group_level`, `improv_type`, `location`, `date_established`)
VALUES
  (1, 'ACME Comedy Theatre', 'Professional', 'Theatresports', 'Los Angeles, California', '1989'),
  (2, 'American Improv Theatre', 'Professional', 'Long-form, Musicals', 'San Jose, California', '2015'),
  (3, 'Awkward Compliment', 'Professional', 'Improvisational', 'Somerville, Massachusetts', '2010'),
  (4, 'The Annoyance Theatre', 'Professional', 'Improvisational', 'Chicago, Illinois', '1987'),
  (5, 'Arcade Comedy Theater', 'Professional', 'Multiple', 'Pittsburgh, Pennsylvania', '2013'),
  (6, 'Atlas Improv Co.', 'Professional', 'Multiple', 'Madison, Wisconsin', '2004'),
  (7, 'Baltimore Improv Group', 'Professional', 'Multiple', 'Baltimore, Maryland', '2004'),
  (8, 'Bay Cities Improv Company', 'Professional', 'Shortform', 'Mobile, Alabama', '2013'),
  (9, 'BATS Improv', 'Major Professional', 'Theatresports', 'San Francisco, California', '1986'),
  (10, 'BETA Theater', 'Professional', 'Multiple', 'Houston, TX', '2013'),
  (11, 'The Bent Theatre', 'Professional', 'Multiple', 'Charlottesville, Virginia', '2004'),
  (12, 'Black Sheep Improv', 'Collegiate', 'Long-Form', 'Athens, Ohio', '2007'),
  (13, 'Bovine Metropolis Theater', 'Professional', 'Multiple', 'Denver, Colorado', '1998'),
  (14, 'Boulder Improv Collaborative', 'Professional', 'Multiple', 'Boulder, Colorado', '2004'),
  (15, 'The Brave New Workshop Comedy Theatre', 'Professional', 'Multiple', 'Minneapolis, Minnesota', '1958'),
  (16, 'Carolina Improv Company', 'Professional', 'Multiple', 'Myrtle Beach, South Carolina', '2008'),
  (17, 'Charlotte Comedy Theater', 'Professional', 'Multiple', 'Charlotte, North Carolina', '2001'),
  (18, 'Charm City Comedy Project', 'Professional', 'Multiple', 'Baltimore, Maryland', '2014'),
  (19, 'CHiPs Improv', 'Collegiate', 'Multiple', 'Chapel Hill, North Carolina', '1995'),
  (20, 'Coalition Theater', 'Professional', 'Multiple', 'Richmond, Virginia', '2009'),
  (21, 'Columbus Unscripted', 'Professional', 'Improvisational', 'Columbus, Ohio', '2006'),
  (22, 'ComedyCity', 'Professional', 'Shortform', 'Green Bay, Wisconsin', '1987'),
  (23, 'Comedy Corner', 'Collegiate', 'Multiple', 'Tucson, Arizona', '1979'),
  (24, 'Commedus Interruptus', 'Collegiate', 'Multiple', 'Los Angeles, California', '1989'),
  (25, 'ComedySportz', 'Major Professional', 'Shortform', 'Milwaukee, Wisconsin', '1984'),
  (26, 'The Crazy Monkeys', 'Collegiate', 'Shortform', 'West Lafayette, Indiana', '1988'),
  (27, 'Dad\'s Garage Theatre Company', 'Professional', 'Multiple', 'Atlanta, Georgia', '1995'),
  (28, 'Defiant Monkey Improv', 'Professional', 'Short-form', 'Buffalo, NY', '2009'),
  (29, 'The Denials', 'The Overtime Theater', 'Short-form', 'San Antonio, Texas', '2009'),
  (30, 'Eclectic Improv Co.', 'Professional', 'Short-Form', 'Buffalo, New York', '1998'),
  (31, 'Endgames Improv', 'Professional', 'Long-Form', 'San Francisco, California', '2010'),
  (32, 'Erasable Inc.', 'Collegiate', 'Improvisational', 'College Park, Maryland', '1986'),
  (33, 'Face Off Unlimited', 'Professional', 'Multiple', 'New York City, New York', '2003'),
  (34, 'False Profits Comedy', 'Collegiate', 'Multiple', 'Chapel Hill, North Carolina', '2013'),
  (35, 'The First Time Offenders', 'Collegiate', 'Multiple', 'San Antonio, TX', '2008'),
  (36, 'The Focus Group', 'Professional', 'Long-form', 'Bangor, Maine', '2009'),
  (37, 'Freudian Slip', 'Collegiate', 'Improvisational', 'College Station, TX', '1994'),
  (38, 'Friday Night Improvs', 'Collegiate', 'Improv Jam', 'Pittsburgh, Pennsylvania', '1989'),
  (39, 'Full Frontal Nudity', 'Professional', 'Multiple', 'Columbus, Ohio', '1993'),
  (40, 'Good On Paper', 'Professional', 'Short-form', 'Traverse City, MI', '2010'),
  (41, 'Groundlings', 'Major Professional', 'Semi-improvisational', 'Los Angeles, California', '1974'),
  (42, 'Harrisburg Improv Theatre', 'Professional', 'Long-form', 'Harrisburg, Pennsylvania', '2014'),
  (43, 'HUGE Theater', 'Professional', 'Long-form', 'Minneapolis, Minnesota', '2005'),
  (44, 'The Immediate Gratification Players', 'Collegiate', 'Long-form', 'Cambridge, Massachusetts', '1986'),
  (45, 'ImprovOlympic', 'Major Professional', 'the Harold', 'Chicago, Illinois', '1980'),
  (46, 'Improv Asylum', 'Major Professional', 'Semi-improvisational', 'Boston, Massachusetts', '1998'),
  (47, 'ImprovBoston', 'Major Professional', 'Multiple', 'Cambridge, Massachusetts', '1982'),
  (48, 'Improv Everywhere', 'Professional', 'Guerrilla', 'New York City, New York', '2001'),
  (49, 'Improv Hawaii', 'Professional', 'Multiple', 'Honolulu, Hawaii', '2012'),
  (50, 'Improvhi', 'Professional', 'Multiple', 'Honolulu, Hawaii', '2012'),
  (51, 'The Improv Shop', 'Professional', 'Improvisational', 'Saint Louis, Missouri', '2009'),
  (52, 'In Between The Lines Comedy Improv Troupe', 'Collegiate', 'Shortform', 'Rochester, New York', '1999'),
  (53, 'Jet City Improv', 'Professional', 'Multiple', 'Seattle, Washington', '1992'),
  (54, 'Just Add Water', 'Collegiate', 'Improvisational', 'New Haven, Connecticut', '1986'),
  (55, 'Just The Funny', 'Professional', 'Multiple', 'Miami, Florida', '1999'),
  (56, 'Laughing Matters', 'Professional', 'Shortform', 'Atlanta, Georgia', '1985'),
  (57, 'Lee County Flannel Club', 'Collegiate', 'Shortform', 'Auburn, Alabama', '2011'),
  (58, 'Leela', 'Professional', 'Multiple', 'San Francisco, California', '2003'),
  (59, 'The Lobby', 'Professional', 'Shortform', 'Fullerton, California', '2005'),
  (60, 'Madcap Theater', 'Professional', 'Shortform', 'Westminster, Colorado', '2006'),
  (61, 'Magnet Theater', 'Major Professional', 'Long-Form', 'New York City, New York', '2005'),
  (62, 'Monkey Business Institute', 'Professional', 'Shortform', 'Madison, Wisconsin', '2004'),
  (63, 'My Mother\'s Fleabag', 'Collegiate', 'Short-form', 'Chestnut Hill, Massachusetts', '1980'),
  (64, 'The N Crowd', 'Professional', 'Shortform', 'Philadelphia, Pennsylvania', '2005'),
  (65, 'The National Comedy Theatre', 'Major Professional', 'Shortform', 'San Diego, California', '2000'),
  (66, 'Odd Lot Improv', 'Professional', 'Shortform', 'Savannah, Georgia', '2010'),
  (67, 'On Thin Ice', 'Collegiate', 'Shortform', 'Cambridge, Massachusetts', '1984'),
  (68, 'Peoples Improv Theater', 'Major Professional', 'Multiple', 'New York City, New York', '2002'),
  (69, 'Philly Improv Theater (PHIT)', 'Major Professional', 'Multiple', 'Philadelphia, Pennsylvania', '2005'),
  (70, 'The Playground', 'Professional', 'Long-form', 'Chicago, Illinois', '1997'),
  (71, 'Providence Improv Guild', 'Professional', 'Multiple', 'Providence, Rhode Island', '2013'),
  (72, 'The Purple Crayon of Yale', 'Collegiate', 'Long-form', 'New Haven, Connecticut', '1985'),
  (73, 'Sacramento Comedy Spot', 'Major Professional', 'Multiple', 'Sacramento, California', '2004'),
  (74, 'SAK Comedy Lab', 'Professional', 'Multiple', 'Orlando, Florida', '1991'),
  (75, 'The San Francisco Improv Alliance', 'Professional', 'Multiple', 'San Francisco, California', '2005'),
  (76, 'The San Francisco Improv Co-Operative', 'Professional', 'Multiple', 'San Francisco, California', '2000'),
  (77, 'San Francisco Improv Collective', 'Professional', 'Multiple', 'San Francisco, California', '2013'),
  (78, 'Sea Tea Improv', 'Professional', 'Multiple', 'Hartford, Connecticut', '2009'),
  (79, 'The Second City', 'Major Professional', 'Semi-improvisational', 'Chicago, Illinois', '1959'),
  (80, 'Second Nature Improv', 'Collegiate', 'Long-form', 'Los Angeles, California', '2002'),
  (81, 'SEE Saw Comedy', 'Professional', 'Multiple', 'Sayville, NY', '2006'),
  (82, 'Sick Puppies Comedy', 'Professional', 'Multiple', 'Boca Raton, Florida', '2012'),
  (83, 'Silverbacks Improv Theatre', 'Professional', 'Multiple', 'Lafayette, Louisiana', '2012'),
  (84, 'State Theatre Improv Fun Force', 'Professional', 'Multiple', 'Eustis, FL', '2015'),
  (85, 'Starla and Sons', 'Collegiate', 'Longform', 'Providence, Rhode Island', '2006'),
  (86, 'Steel City Improv Theater', 'Professional', 'Longform', 'Pittsburgh, PA', '2010'),
  (87, 'Syracuse Improv Collective', 'Professional', 'Multiple', 'Syracuse, New York', '2011'),
  (88, 'Theatre 99', 'Professional', 'Multiple', 'Charleston, South Carolina', '2000'),
  (89, 'Theatre Strike Force', 'Collegiate', 'Multiple', 'Gainesville, Florida', '1989'),
  (90, 'Tucson Improv Movement', 'Professional', 'Multiple', 'Tucson, Arizona', '2012'),
  (91, 'The National Comedy Theatre', 'Professional', 'Multiple', 'Phoenix, Arizona', '2007'),
  (92, 'Unexpected Company', 'Professional', 'Long-form', 'Warwick, Rhode Island', '2003'),
  (93, 'Unexpected Productions', 'Professional', 'Theatresports', 'Seattle, Washington', '1983'),
  (94, 'Under the Gun Theater', 'Professional', 'Multiple', 'Chicago, Illinois', '2014'),
  (95, 'The Un-Scripted Theater Company', 'Professional', 'Multiple', 'San Francisco, California', '2002'),
  (96, 'Upright Citizens Brigade', 'Major Professional', 'Multiple', 'New York City, New York', '1999'),
  (97, 'Vaudeville Performing Arts (Vaudeville Central Florida)', 'Professional', 'Short Form/Improvisational', 'Orlando, Florida', '2015'),
  (98, 'Washington Improv Theater', 'Major Professional', 'Long-form', 'Washington, DC', '1995'),
  (99, 'Whole World Theatre', 'Professional', 'Shortform', 'Atlanta, Georgia', '1994'),
  (100, 'Wing-It Productions', 'Professional', 'Multiple', 'Seattle, Washington', '1992'),
  (101, 'The Yale Ex!t Players', 'Collegiate', 'Short-form', 'New Haven, Connecticut', '1984'),
  (102, 'WHIP Comedy Improv', 'Collegiate', 'Multiple', 'Westfield, Massachusetts', '2012');
