INSERT INTO `gameinfo` (`game_id`, `game_name`, `instructions`, `category`, `avg_rating`, `min_players`, `max_players`, `date`)
VALUES
  (1, 'Zip Zap Zop', 'Zip, Zap, Zop is about focus and energy. As students pass the energy across the circle (in the form of a Zip, a Zap, or a Zop), they make eye contact with the person they send the energy to, and work together to keep the rhythm going. The activity also provides an opportunity to explore pace, specificity of choice, “energy” and sequence.\n\nInvite students to stand in a circle. Ask the group to repeat the words “Zip, Zap, Zop” three or four times, all together. Introduce the activity: Imagine that I have a bolt of energy in my hands. To start the game, I will send the bolt out of energy out of my body with a strong forward motion straight to someone else in the circle (use hands, body, eyes, and voice to make contact across the circle) and say, “Zip.” Explain that the next person takes the energy and passes it immediately to someone else saying “Zap.” That person passes it on to another participant with a “Zop.” The game continues and the “Zip, Zap, Zop” sequence is repeated as the energy moves around the circle.  Encourage all plays to use their whole body to send energy and to make eye contact. They can send the energy to whomever they want but the goal is to include all players. Practice the game. If there is a mistake, encourage students to simply resume playing without discussion. The group challenge is to go very quickly and stay consistent in rhythm; if students struggle, pause the game, discuss strategy and try again.', 'Warmup', NULL, 3, NULL, '2017-05-25 17:56:53'),
  (2, 'Lines from the Floor', 'Before the show, ask the audience to write simple sentences on slips of paper. Anything goes.\nThe game is played by 2 players. Ask for a location, or a profession, and have every player draw 3 of these slips. Players put these in their pockets without reading them.\n\nThen a scene is played, in which at any point in time, players replace what they might have said, by whatever is on the piece of paper they draw out of their pocket. Try to incorporate/justify whatever is your line into the scene.\n\nTry to avoid thinks like `My granny always said` - you want your character to say whatever is on the piece of paper - don`t try to put those words into someone else`s mouth. See also a game called Bucket that uses audience lines as well.', 'Limitations', NULL, 2, NULL, '2017-05-25 18:01:09'),
  (3, 'Yes Let\'s', 'Pick a group activity, like throwing a party or organizing a picnic. One player starts, saying \"Let`s ...\" filling in what she wants to do. Then she starts actually doing what she said she wanted to do. A second player jumps in, saying \"Let`s ...\" do something else, to advance the group activity. Both players say \"Yes, let`s do that\" and start doing whatever suggested. Third player jumps in, suggests what to do, and again all players loudly agree to do it, and actually do it. Continue till everyone has suggested something.', 'Warmup', NULL, 2, NULL, '2017-05-25 18:03:45'),
  (4, 'The Oracle', 'One person is the interviewer, and the rest of the players are one \"oracle\" with multiple heads. The interviewer asks questions to the Oracle, and the Oracle provides answers word by word, from each player at a time. You can also have the audience ask the oracle questions about life, love, hardships, etc.', 'Limitations', NULL, 4, NULL, '2017-05-25 18:15:49'),
  (5, 'Five Things', 'One player leaves the room. The audience suggests a sport, activity, or event. Then five things are changed about it based on audience suggestions. For example, if the activity is \"playing tennis\", then the ref might ask \"Instead of a court, they are playing on a\" and the audience will suggest something different. Once five things have been changed, the player comes back in and has to guess the activity and the five new things about it from the pantomime and gibberish from the other two players.', 'Guessing', NULL, 3, NULL, '2017-05-25 19:00:41');


