
INSERT INTO iMachine(Relationship) VALUES ('$5 Bill and $100 Bill');
INSERT INTO iMachine(Relationship) VALUES ('Actor and Director');
INSERT INTO iMachine(Relationship) VALUES ('Actor and Double');
INSERT INTO iMachine(Relationship) VALUES ('Aging Lovers');
INSERT INTO iMachine(Relationship) VALUES ('Alice and the White Rabbit');
INSERT INTO iMachine(Relationship) VALUES ('Astronaut and Alien');
INSERT INTO iMachine(Relationship) VALUES ('Batman and Robin');
INSERT INTO iMachine(Relationship) VALUES ('Blood cell and Bacterium');
INSERT INTO iMachine(Relationship) VALUES ('Brother and Sister');
INSERT INTO iMachine(Relationship) VALUES ('Buddha and Christ');
INSERT INTO iMachine(Relationship) VALUES ('Bus Driver and Passenger');
INSERT INTO iMachine(Relationship) VALUES ('Celebrity and Fan');
INSERT INTO iMachine(Relationship) VALUES ('Contestant and Game Show Host');
INSERT INTO iMachine(Relationship) VALUES ('Cosmetic Surgeon and Supermodel');
INSERT INTO iMachine(Relationship) VALUES ('Cowboy and Indian');
INSERT INTO iMachine(Relationship) VALUES ('Defendant and Judge');
INSERT INTO iMachine(Relationship) VALUES ('Demon and Angel');
INSERT INTO iMachine(Relationship) VALUES ('Detective and Criminal');
INSERT INTO iMachine(Relationship) VALUES ('Director and Producer');
INSERT INTO iMachine(Relationship) VALUES ('Doctor and Nurse');
INSERT INTO iMachine(Relationship) VALUES ('Doctor and Patient');
INSERT INTO iMachine(Relationship) VALUES ('Dog and Bone');
INSERT INTO iMachine(Relationship) VALUES ('Ex-husband and New Man');
INSERT INTO iMachine(Relationship) VALUES ('Ex-wife and New Woman');
INSERT INTO iMachine(Relationship) VALUES ('Father / Child');
INSERT INTO iMachine(Relationship) VALUES ('Fish and Worm');
INSERT INTO iMachine(Relationship) VALUES ('Frog and Princess');
INSERT INTO iMachine(Relationship) VALUES ('Gay Couple');
INSERT INTO iMachine(Relationship) VALUES ('God and Devil');
INSERT INTO iMachine(Relationship) VALUES ('God and Mortal');
INSERT INTO iMachine(Relationship) VALUES ('Good Conscience and Bad Conscience');
INSERT INTO iMachine(Relationship) VALUES ('Grandparent and Grandchild');
INSERT INTO iMachine(Relationship) VALUES ('Guard and Prisoner');
INSERT INTO iMachine(Relationship) VALUES ('Hairdresser and Customer');
INSERT INTO iMachine(Relationship) VALUES ('Judge and Lawyer');
INSERT INTO iMachine(Relationship) VALUES ('Lawyer and Client');
INSERT INTO iMachine(Relationship) VALUES ('Love Triangle');
INSERT INTO iMachine(Relationship) VALUES ('Married Couple');
INSERT INTO iMachine(Relationship) VALUES ('Mechanic and Customer');
INSERT INTO iMachine(Relationship) VALUES ('Mother / Child');
INSERT INTO iMachine(Relationship) VALUES ('Mother-in-law and Daughter-in-law / Son');
INSERT INTO iMachine(Relationship) VALUES ('PC and User');
INSERT INTO iMachine(Relationship) VALUES ('Pilot and CoPilot');
INSERT INTO iMachine(Relationship) VALUES ('Pilot and Crewmember');
INSERT INTO iMachine(Relationship) VALUES ('Pilot and Passenger');
INSERT INTO iMachine(Relationship) VALUES ('Policeman and Driver');
INSERT INTO iMachine(Relationship) VALUES ('Politician and Voter');
INSERT INTO iMachine(Relationship) VALUES ('Pope and Cardinal');
INSERT INTO iMachine(Relationship) VALUES ('President and Cabinet');
INSERT INTO iMachine(Relationship) VALUES ('Priest and Altar Boy');
INSERT INTO iMachine(Relationship) VALUES ('Priest and Parishioner');
INSERT INTO iMachine(Relationship) VALUES ('Psychiatrist and Patient');
INSERT INTO iMachine(Relationship) VALUES ('Psychopath and Victim');
INSERT INTO iMachine(Relationship) VALUES ('Rat and Lab Scientist');
INSERT INTO iMachine(Relationship) VALUES ('Robot and Creator');
INSERT INTO iMachine(Relationship) VALUES ('Seller and Buyer');
INSERT INTO iMachine(Relationship) VALUES ('Sheriff and Gangster');
INSERT INTO iMachine(Relationship) VALUES ('Spermium and Egg cell');
INSERT INTO iMachine(Relationship) VALUES ('Step-parent(s) / Stepchild');
INSERT INTO iMachine(Relationship) VALUES ('Tailor and Customer');
INSERT INTO iMachine(Relationship) VALUES ('Taxi Drivers and Customer');
INSERT INTO iMachine(Relationship) VALUES ('Teacher and Headmaster');
INSERT INTO iMachine(Relationship) VALUES ('Teacher and Parent(s)');
INSERT INTO iMachine(Relationship) VALUES ('Teacher and Pupil');
INSERT INTO iMachine(Relationship) VALUES ('Terrorist and Hostage');
INSERT INTO iMachine(Relationship) VALUES ('The First Engagement');
INSERT INTO iMachine(Relationship) VALUES ('Ventriloquist and Doll');
INSERT INTO iMachine(Relationship) VALUES ('Veterinarian and Pet');
INSERT INTO iMachine(Relationship) VALUES ('Veterinarian and Pet Owner');
INSERT INTO iMachine(Relationship) VALUES ('Waiter and Guest');

INSERT INTO iMachine(Thing) VALUES ('Air Freshener');
INSERT INTO iMachine(Thing) VALUES ('Apple');
INSERT INTO iMachine(Thing) VALUES ('Bag');
INSERT INTO iMachine(Thing) VALUES ('Balloon');
INSERT INTO iMachine(Thing) VALUES ('Bananas');
INSERT INTO iMachine(Thing) VALUES ('Bed');
INSERT INTO iMachine(Thing) VALUES ('Beef');
INSERT INTO iMachine(Thing) VALUES ('Blanket');
INSERT INTO iMachine(Thing) VALUES ('Blouse');
INSERT INTO iMachine(Thing) VALUES ('Book');
INSERT INTO iMachine(Thing) VALUES ('Bookmark');
INSERT INTO iMachine(Thing) VALUES ('Boom Box');
INSERT INTO iMachine(Thing) VALUES ('Bottle');
INSERT INTO iMachine(Thing) VALUES ('Bottle Cap');
INSERT INTO iMachine(Thing) VALUES ('Bow');
INSERT INTO iMachine(Thing) VALUES ('Bowl');
INSERT INTO iMachine(Thing) VALUES ('Box');
INSERT INTO iMachine(Thing) VALUES ('Bracelet');
INSERT INTO iMachine(Thing) VALUES ('Bread');
INSERT INTO iMachine(Thing) VALUES ('Broccoli');
INSERT INTO iMachine(Thing) VALUES ('Button');
INSERT INTO iMachine(Thing) VALUES ('Camera');
INSERT INTO iMachine(Thing) VALUES ('Candle');
INSERT INTO iMachine(Thing) VALUES ('Candy Wrapper');
INSERT INTO iMachine(Thing) VALUES ('Canvas');
INSERT INTO iMachine(Thing) VALUES ('Car');
INSERT INTO iMachine(Thing) VALUES ('Carrots');
INSERT INTO iMachine(Thing) VALUES ('Cat');
INSERT INTO iMachine(Thing) VALUES ('CD');
INSERT INTO iMachine(Thing) VALUES ('Cell Phone');
INSERT INTO iMachine(Thing) VALUES ('Chair');
INSERT INTO iMachine(Thing) VALUES ('Chalk');
INSERT INTO iMachine(Thing) VALUES ('Chapter Book');
INSERT INTO iMachine(Thing) VALUES ('Charger');
INSERT INTO iMachine(Thing) VALUES ('Checkbook');
INSERT INTO iMachine(Thing) VALUES ('Chocolate');
INSERT INTO iMachine(Thing) VALUES ('Clamp');
INSERT INTO iMachine(Thing) VALUES ('Clay Pot');
INSERT INTO iMachine(Thing) VALUES ('Clock');
INSERT INTO iMachine(Thing) VALUES ('Clothes');
INSERT INTO iMachine(Thing) VALUES ('Coasters');
INSERT INTO iMachine(Thing) VALUES ('Computer');
INSERT INTO iMachine(Thing) VALUES ('Conditioner');
INSERT INTO iMachine(Thing) VALUES ('Controller');
INSERT INTO iMachine(Thing) VALUES ('Cookie Jar');
INSERT INTO iMachine(Thing) VALUES ('Cork');
INSERT INTO iMachine(Thing) VALUES ('Couch');
INSERT INTO iMachine(Thing) VALUES ('Credit Card');
INSERT INTO iMachine(Thing) VALUES ('Cup');
INSERT INTO iMachine(Thing) VALUES ('Deodorant');
INSERT INTO iMachine(Thing) VALUES ('Desk');
INSERT INTO iMachine(Thing) VALUES ('Doll');
INSERT INTO iMachine(Thing) VALUES ('Door');
INSERT INTO iMachine(Thing) VALUES ('Drawer');
INSERT INTO iMachine(Thing) VALUES ('Drill Press');
INSERT INTO iMachine(Thing) VALUES ('Eraser');
INSERT INTO iMachine(Thing) VALUES ('Eye Liner');
INSERT INTO iMachine(Thing) VALUES ('Fake Flowers');
INSERT INTO iMachine(Thing) VALUES ('Flag');
INSERT INTO iMachine(Thing) VALUES ('Floor');
INSERT INTO iMachine(Thing) VALUES ('Flowers');
INSERT INTO iMachine(Thing) VALUES ('Food');
INSERT INTO iMachine(Thing) VALUES ('Fork');
INSERT INTO iMachine(Thing) VALUES ('Fridge');
INSERT INTO iMachine(Thing) VALUES ('Glass');
INSERT INTO iMachine(Thing) VALUES ('Glasses');
INSERT INTO iMachine(Thing) VALUES ('Glow Stick');
INSERT INTO iMachine(Thing) VALUES ('Greeting Card');
INSERT INTO iMachine(Thing) VALUES ('Grid Paper');
INSERT INTO iMachine(Thing) VALUES ('Hair Tie');
INSERT INTO iMachine(Thing) VALUES ('Hanger');
INSERT INTO iMachine(Thing) VALUES ('Headphones');
INSERT INTO iMachine(Thing) VALUES ('Helmet');
INSERT INTO iMachine(Thing) VALUES ('House');
INSERT INTO iMachine(Thing) VALUES ('Ice Cube Tray');
INSERT INTO iMachine(Thing) VALUES ('iPod');
INSERT INTO iMachine(Thing) VALUES ('Keyboard');
INSERT INTO iMachine(Thing) VALUES ('Keychain');
INSERT INTO iMachine(Thing) VALUES ('Keys');
INSERT INTO iMachine(Thing) VALUES ('Knife');
INSERT INTO iMachine(Thing) VALUES ('Lace');
INSERT INTO iMachine(Thing) VALUES ('Lamp');
INSERT INTO iMachine(Thing) VALUES ('Lamp Shade');
INSERT INTO iMachine(Thing) VALUES ('Leg Warmers');
INSERT INTO iMachine(Thing) VALUES ('Lip Gloss');
INSERT INTO iMachine(Thing) VALUES ('Lotion');
INSERT INTO iMachine(Thing) VALUES ('Magnet');
INSERT INTO iMachine(Thing) VALUES ('Milk');
INSERT INTO iMachine(Thing) VALUES ('Mirror');
INSERT INTO iMachine(Thing) VALUES ('Model Car');
INSERT INTO iMachine(Thing) VALUES ('Money');
INSERT INTO iMachine(Thing) VALUES ('Monitor');
INSERT INTO iMachine(Thing) VALUES ('Mop');
INSERT INTO iMachine(Thing) VALUES ('Mouse Pad');
INSERT INTO iMachine(Thing) VALUES ('MP3 Player');
INSERT INTO iMachine(Thing) VALUES ('Nail Clippers');
INSERT INTO iMachine(Thing) VALUES ('Nail File');
INSERT INTO iMachine(Thing) VALUES ('Needle');
INSERT INTO iMachine(Thing) VALUES ('Newspaper');
INSERT INTO iMachine(Thing) VALUES ('Outlet');
INSERT INTO iMachine(Thing) VALUES ('Packing Peanuts');
INSERT INTO iMachine(Thing) VALUES ('Paint Brush');
INSERT INTO iMachine(Thing) VALUES ('Pants');
INSERT INTO iMachine(Thing) VALUES ('Paper');
INSERT INTO iMachine(Thing) VALUES ('Pen');
INSERT INTO iMachine(Thing) VALUES ('Pencil');
INSERT INTO iMachine(Thing) VALUES ('Perfume');
INSERT INTO iMachine(Thing) VALUES ('Phone');
INSERT INTO iMachine(Thing) VALUES ('Photo Album');
INSERT INTO iMachine(Thing) VALUES ('Piano');
INSERT INTO iMachine(Thing) VALUES ('Picture Frame');
INSERT INTO iMachine(Thing) VALUES ('Pillow');
INSERT INTO iMachine(Thing) VALUES ('Plastic Fork');
INSERT INTO iMachine(Thing) VALUES ('Plate');
INSERT INTO iMachine(Thing) VALUES ('Playing Card');
INSERT INTO iMachine(Thing) VALUES ('Pool Stick');
INSERT INTO iMachine(Thing) VALUES ('Post-it Note');
INSERT INTO iMachine(Thing) VALUES ('Puddle');
INSERT INTO iMachine(Thing) VALUES ('Purse');
INSERT INTO iMachine(Thing) VALUES ('Radio');
INSERT INTO iMachine(Thing) VALUES ('Remote');
INSERT INTO iMachine(Thing) VALUES ('Ring');
INSERT INTO iMachine(Thing) VALUES ('Rubber Band');
INSERT INTO iMachine(Thing) VALUES ('Rubber Duck');
INSERT INTO iMachine(Thing) VALUES ('Rug');
INSERT INTO iMachine(Thing) VALUES ('Rusty Nail');
INSERT INTO iMachine(Thing) VALUES ('Sailboat');
INSERT INTO iMachine(Thing) VALUES ('Sand Paper');
INSERT INTO iMachine(Thing) VALUES ('Sandal');
INSERT INTO iMachine(Thing) VALUES ('Scotch Tape');
INSERT INTO iMachine(Thing) VALUES ('Screw');
INSERT INTO iMachine(Thing) VALUES ('Seat Belt');
INSERT INTO iMachine(Thing) VALUES ('Shampoo');
INSERT INTO iMachine(Thing) VALUES ('Sharpie');
INSERT INTO iMachine(Thing) VALUES ('Shirt');
INSERT INTO iMachine(Thing) VALUES ('Shoes');
INSERT INTO iMachine(Thing) VALUES ('Shovel');
INSERT INTO iMachine(Thing) VALUES ('Sidewalk');
INSERT INTO iMachine(Thing) VALUES ('Sketch Pad');
INSERT INTO iMachine(Thing) VALUES ('Slipper');
INSERT INTO iMachine(Thing) VALUES ('Soap');
INSERT INTO iMachine(Thing) VALUES ('Socks');
INSERT INTO iMachine(Thing) VALUES ('Soda Can');
INSERT INTO iMachine(Thing) VALUES ('Sofa');
INSERT INTO iMachine(Thing) VALUES ('Soy Sauce Packet');
INSERT INTO iMachine(Thing) VALUES ('Speakers');
INSERT INTO iMachine(Thing) VALUES ('Sponge');
INSERT INTO iMachine(Thing) VALUES ('Spoon');
INSERT INTO iMachine(Thing) VALUES ('Spring');
INSERT INTO iMachine(Thing) VALUES ('Stockings');
INSERT INTO iMachine(Thing) VALUES ('Stop Sign');
INSERT INTO iMachine(Thing) VALUES ('Street Lights');
INSERT INTO iMachine(Thing) VALUES ('Sun Glasses');
INSERT INTO iMachine(Thing) VALUES ('Table');
INSERT INTO iMachine(Thing) VALUES ('Teddy Bear');
INSERT INTO iMachine(Thing) VALUES ('Thermometer');
INSERT INTO iMachine(Thing) VALUES ('Thermostat');
INSERT INTO iMachine(Thing) VALUES ('Thread');
INSERT INTO iMachine(Thing) VALUES ('Tire Swing');
INSERT INTO iMachine(Thing) VALUES ('Toe Ring');
INSERT INTO iMachine(Thing) VALUES ('Toilet');
INSERT INTO iMachine(Thing) VALUES ('Tomato');
INSERT INTO iMachine(Thing) VALUES ('Toothbrush');
INSERT INTO iMachine(Thing) VALUES ('Toothpaste');
INSERT INTO iMachine(Thing) VALUES ('Toothpicks');
INSERT INTO iMachine(Thing) VALUES ('Towel');
INSERT INTO iMachine(Thing) VALUES ('Tree');
INSERT INTO iMachine(Thing) VALUES ('Truck');
INSERT INTO iMachine(Thing) VALUES ('TV');
INSERT INTO iMachine(Thing) VALUES ('Tweezers');
INSERT INTO iMachine(Thing) VALUES ('USB Drive');
INSERT INTO iMachine(Thing) VALUES ('Vase');
INSERT INTO iMachine(Thing) VALUES ('Video Games');
INSERT INTO iMachine(Thing) VALUES ('Wagon');
INSERT INTO iMachine(Thing) VALUES ('Wallet');
INSERT INTO iMachine(Thing) VALUES ('Washing Machine');
INSERT INTO iMachine(Thing) VALUES ('Watch');
INSERT INTO iMachine(Thing) VALUES ('Water Bottle');
INSERT INTO iMachine(Thing) VALUES ('White Out');
INSERT INTO iMachine(Thing) VALUES ('Window');
INSERT INTO iMachine(Thing) VALUES ('Zipper');

INSERT INTO iMachine(Place) VALUES ('Adoption Clinic');
INSERT INTO iMachine(Place) VALUES ('Ambulance');
INSERT INTO iMachine(Place) VALUES ('Antique Store');
INSERT INTO iMachine(Place) VALUES ('Art Gallery');
INSERT INTO iMachine(Place) VALUES ('Attic');
INSERT INTO iMachine(Place) VALUES ('Australian Outback');
INSERT INTO iMachine(Place) VALUES ('Back Yard');
INSERT INTO iMachine(Place) VALUES ('Bad Neighborhood');
INSERT INTO iMachine(Place) VALUES ('Bakery');
INSERT INTO iMachine(Place) VALUES ('Balcony');
INSERT INTO iMachine(Place) VALUES ('Barbershop');
INSERT INTO iMachine(Place) VALUES ('Beaver Dam');
INSERT INTO iMachine(Place) VALUES ('Bird''s Nest');
INSERT INTO iMachine(Place) VALUES ('Boat');
INSERT INTO iMachine(Place) VALUES ('Bootcamp');
INSERT INTO iMachine(Place) VALUES ('Butterly Habitat');
INSERT INTO iMachine(Place) VALUES ('Cafe');
INSERT INTO iMachine(Place) VALUES ('Castle');
INSERT INTO iMachine(Place) VALUES ('Cat Lady''s House');
INSERT INTO iMachine(Place) VALUES ('Cave');
INSERT INTO iMachine(Place) VALUES ('Cheese Factory');
INSERT INTO iMachine(Place) VALUES ('Chiropractor''s Office');
INSERT INTO iMachine(Place) VALUES ('Circus');
INSERT INTO iMachine(Place) VALUES ('Classroom');
INSERT INTO iMachine(Place) VALUES ('Dance Studio');
INSERT INTO iMachine(Place) VALUES ('Department of Motor Vehicles');
INSERT INTO iMachine(Place) VALUES ('Desert');
INSERT INTO iMachine(Place) VALUES ('Dragon''s Lair');
INSERT INTO iMachine(Place) VALUES ('Egypt');
INSERT INTO iMachine(Place) VALUES ('Elephant Sanctuary');
INSERT INTO iMachine(Place) VALUES ('Execution Chamber');
INSERT INTO iMachine(Place) VALUES ('Fire Station');
INSERT INTO iMachine(Place) VALUES ('Fishing Pond');
INSERT INTO iMachine(Place) VALUES ('Football Stadium');
INSERT INTO iMachine(Place) VALUES ('Fortune Teller''s Shop');
INSERT INTO iMachine(Place) VALUES ('Front Yard');
INSERT INTO iMachine(Place) VALUES ('Garage');
INSERT INTO iMachine(Place) VALUES ('Garbage Dump');
INSERT INTO iMachine(Place) VALUES ('Ghost Town');
INSERT INTO iMachine(Place) VALUES ('Goldmine');
INSERT INTO iMachine(Place) VALUES ('Golf Course');
INSERT INTO iMachine(Place) VALUES ('Gondola');
INSERT INTO iMachine(Place) VALUES ('Grand Canyon');
INSERT INTO iMachine(Place) VALUES ('Grocery Store');
INSERT INTO iMachine(Place) VALUES ('Gypsy Camp');
INSERT INTO iMachine(Place) VALUES ('Hardware Store');
INSERT INTO iMachine(Place) VALUES ('Hawaii');
INSERT INTO iMachine(Place) VALUES ('Helicopter Pad');
INSERT INTO iMachine(Place) VALUES ('Henhouse');
INSERT INTO iMachine(Place) VALUES ('Hogwarts');
INSERT INTO iMachine(Place) VALUES ('Hospital');
INSERT INTO iMachine(Place) VALUES ('Ice Cream Shop');
INSERT INTO iMachine(Place) VALUES ('Iceberg');
INSERT INTO iMachine(Place) VALUES ('Igloo');
INSERT INTO iMachine(Place) VALUES ('Inside a Blimp');
INSERT INTO iMachine(Place) VALUES ('Jet Pilot''s Cockpit');
INSERT INTO iMachine(Place) VALUES ('Jewelry Store');
INSERT INTO iMachine(Place) VALUES ('Judge''s Chambers');
INSERT INTO iMachine(Place) VALUES ('Jungle');
INSERT INTO iMachine(Place) VALUES ('Jury Box');
INSERT INTO iMachine(Place) VALUES ('Kangaroo Farm');
INSERT INTO iMachine(Place) VALUES ('Karaoke Bar');
INSERT INTO iMachine(Place) VALUES ('Karate Class');
INSERT INTO iMachine(Place) VALUES ('King Kong''s Cage');
INSERT INTO iMachine(Place) VALUES ('Lagoon');
INSERT INTO iMachine(Place) VALUES ('Laundromat');
INSERT INTO iMachine(Place) VALUES ('Library');
INSERT INTO iMachine(Place) VALUES ('Lifeboat');
INSERT INTO iMachine(Place) VALUES ('Lighthouse');
INSERT INTO iMachine(Place) VALUES ('London');
INSERT INTO iMachine(Place) VALUES ('Make-up Counter');
INSERT INTO iMachine(Place) VALUES ('Marathon Finish Line');
INSERT INTO iMachine(Place) VALUES ('Mechanic''s Shop');
INSERT INTO iMachine(Place) VALUES ('Middle of the Sea');
INSERT INTO iMachine(Place) VALUES ('Moon');
INSERT INTO iMachine(Place) VALUES ('Mountain Top');
INSERT INTO iMachine(Place) VALUES ('Mummy''s Tomb');
INSERT INTO iMachine(Place) VALUES ('Nature Trail');
INSERT INTO iMachine(Place) VALUES ('Neverland');
INSERT INTO iMachine(Place) VALUES ('News Station');
INSERT INTO iMachine(Place) VALUES ('Newspaper Office');
INSERT INTO iMachine(Place) VALUES ('Nightclub');
INSERT INTO iMachine(Place) VALUES ('Nursing Home');
INSERT INTO iMachine(Place) VALUES ('Office Cubicle');
INSERT INTO iMachine(Place) VALUES ('Open House');
INSERT INTO iMachine(Place) VALUES ('Optometrist');
INSERT INTO iMachine(Place) VALUES ('Orchard');
INSERT INTO iMachine(Place) VALUES ('Orchestra Pit');
INSERT INTO iMachine(Place) VALUES ('Panda Exhibit');
INSERT INTO iMachine(Place) VALUES ('Pet Store');
INSERT INTO iMachine(Place) VALUES ('Photography Class');
INSERT INTO iMachine(Place) VALUES ('Picnic Spot');
INSERT INTO iMachine(Place) VALUES ('Pirate Ship');
INSERT INTO iMachine(Place) VALUES ('Police Station');
INSERT INTO iMachine(Place) VALUES ('Post Office');
INSERT INTO iMachine(Place) VALUES ('Prom');
INSERT INTO iMachine(Place) VALUES ('Rainforest');
INSERT INTO iMachine(Place) VALUES ('Recording Studio');
INSERT INTO iMachine(Place) VALUES ('Red Carpet');
INSERT INTO iMachine(Place) VALUES ('Restaurant');
INSERT INTO iMachine(Place) VALUES ('Riverboat');
INSERT INTO iMachine(Place) VALUES ('Santa''s Workshop');
INSERT INTO iMachine(Place) VALUES ('School Lunchroom');
INSERT INTO iMachine(Place) VALUES ('School Nurse''s Office');
INSERT INTO iMachine(Place) VALUES ('Ski Slope');
INSERT INTO iMachine(Place) VALUES ('Smurf Village');
INSERT INTO iMachine(Place) VALUES ('Softball Game');
INSERT INTO iMachine(Place) VALUES ('Spaceship');
INSERT INTO iMachine(Place) VALUES ('Spaceship');
INSERT INTO iMachine(Place) VALUES ('Stable');
INSERT INTO iMachine(Place) VALUES ('State Fair');
INSERT INTO iMachine(Place) VALUES ('Submarine');
INSERT INTO iMachine(Place) VALUES ('Summer Camp');
INSERT INTO iMachine(Place) VALUES ('Thrift Store');
INSERT INTO iMachine(Place) VALUES ('Tidepool');
INSERT INTO iMachine(Place) VALUES ('Travel Agency');
INSERT INTO iMachine(Place) VALUES ('Treehouse');
INSERT INTO iMachine(Place) VALUES ('Tropical Island');
INSERT INTO iMachine(Place) VALUES ('Truckstop');
INSERT INTO iMachine(Place) VALUES ('TV Show Set');
INSERT INTO iMachine(Place) VALUES ('Underground');
INSERT INTO iMachine(Place) VALUES ('Underwater');
INSERT INTO iMachine(Place) VALUES ('Unemployment Office');
INSERT INTO iMachine(Place) VALUES ('Unicorn Forest');
INSERT INTO iMachine(Place) VALUES ('Utopian Society');
INSERT INTO iMachine(Place) VALUES ('Vampire''s Home');
INSERT INTO iMachine(Place) VALUES ('Volcano');
INSERT INTO iMachine(Place) VALUES ('Volleyball Court');
INSERT INTO iMachine(Place) VALUES ('Voting Booth');
INSERT INTO iMachine(Place) VALUES ('Warehouse');
INSERT INTO iMachine(Place) VALUES ('Water Park');
INSERT INTO iMachine(Place) VALUES ('Wedding Chapel');
INSERT INTO iMachine(Place) VALUES ('Western Saloon');
INSERT INTO iMachine(Place) VALUES ('White House');
INSERT INTO iMachine(Place) VALUES ('Witch''s Cavern');
INSERT INTO iMachine(Place) VALUES ('Wrestling Ring');
INSERT INTO iMachine(Place) VALUES ('X-Ray Lab');
INSERT INTO iMachine(Place) VALUES ('Yoga Studio');
INSERT INTO iMachine(Place) VALUES ('Zombie Vacation Spot');
INSERT INTO iMachine(Place) VALUES ('Zoo');
